server:
  port: 8080

datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/sample?createDatabaseIfNotExist=true
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

management:
  security:
    enabled: false
  endpoints:
    jmx:
      domain: com.example.springboot
      unique-names: true
    web:
      exposure:
        include: "*"

spring:
  application:
    name: SpringBootCRUDApp
  boot:
    admin:
      url: http://localhost:9763/${spring.application.name}
      context-path: /admin
      client:
        service-url: http://localhost:9763/${spring.application.name}
  jackson:
    serialization:
      INDENT_OUTPUT: true

