server:
  port: 8080

datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/sample?createDatabaseIfNotExist=true
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  boot:
    admin:
      url: http://localhost:8081
  jackson:
    serialization:
      INDENT_OUTPUT: true

